name: cpacsSeminar
channels:
  - dlr-sc
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - tixi3
  - tigl3
  - lxml
  - matplotlib
  - pytest
  - pythreejs=2.4.2
  - jupyter
  - ipydatawidgets=4.3.2
  - ipykernel=6.21.2
  - ipython=8.12.0 
  - ipywidgets=7.7.2
  - jupyter=1.0.0
  - jupyterlab=3.6.1
  - jupyterlab_widgets=1.1.1
  - notebook=6.5.2
